"""added token to the db

Revision ID: 116ad71c59f5
Revises: 0d956ceccdcb
Create Date: 2024-09-09 17:49:32.371109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116ad71c59f5'
down_revision = '0d956ceccdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
